---
# tasks file for terraforming - Debian

- name: "Installing {{ ruby_app_debian_package }} on Debian based systems as required for {{ terraforming_app }}"
  package:
    name: "{{ ruby_app_debian_package }}"
    state: "{{ ruby_desired_state }}"
    force_apt_get: yes
    update_cache: yes

- name: "Installing {{ terraforming_app }} on Debian based systems"
  gem:
    name: "{{ terraforming_app }}"
    state: "{{ terraforming_desired_state }}"
    user_install: "{{ terraforming_user_install }}"
    include_dependencies: "{{ terraforming_include_dependencies }}"
